language: node_js # 언어는 node_js
node_js:
  - "12.18" # node_js version
before_install: # 패키지를 다운로드 받기 전
  - npm install -g pm2  # yarn을 글로벌로 설치
branches:
  only:
    - master
notifications: # 성공 실패 여부 알림 
  email:
    recipients:
      - jiduckche.com@gmail.com